apiVersion: v1
kind: Service
metadata:
  name: agente-app
  namespace: agente
spec:
  type: LoadBalancer
  selector:
    app: agente-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
